// Comprehensive EA FC Player Database generated from spreadsheet
const PLAYERS_DATABASE = [
    {
        "id": "p_1",
        "name": "Thibaut Courtois",
        "category": "Goalkeepers (GK)",
        "basePrice": "\u20b95M",
        "nation": "BELGIUM",
        "flagImg": "Flag_of_Belgium.svg",
        "pos": "GK",
        "rating": 89,
        "club": "REAL MADRID",
        "clubImg": "Real_Madrid_logo.svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Thibaut Courtois.png",
        "image": "Thibaut Courtois.jpeg",
        "noBgImage": "no_bg/Thibaut Courtois.png",
        "flag": "Flag_of_Belgium.svg",
        "clubLogo": "Real_Madrid_logo.svg",
        "leagueLogo": "LaLiga_EA_Sports_2023_Vertical_Logo.svg"
    },
    {
        "id": "p_2",
        "name": "Gianluigi Donnarumma",
        "category": "Goalkeepers (GK)",
        "basePrice": "\u20b95M",
        "nation": "ITALY",
        "flagImg": "Flag_of_Italy.svg",
        "pos": "GK",
        "rating": 89,
        "club": "MANCHESTER CITY",
        "clubImg": "Manchester_City_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Gianluigi Donnarumma.png",
        "image": "Gianluigi Donnarumma.jpeg",
        "noBgImage": "no_bg/Gianluigi Donnarumma.png",
        "flag": "Flag_of_Italy.svg",
        "clubLogo": "Manchester_City_FC.svg",
        "leagueLogo": "Premier_League_Logo.svg"
    },
    {
        "id": "p_3",
        "name": "Alisson",
        "category": "Goalkeepers (GK)",
        "basePrice": "\u20b95M",
        "nation": "BRAZIL",
        "flagImg": "Flag_of_Brazil.svg",
        "pos": "GK",
        "rating": 89,
        "club": "LIVERPOOL",
        "clubImg": "Liverpool_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Alison.png",
        "image": "Alison.jpeg",
        "noBgImage": "no_bg/Alison.png",
        "flag": "Flag_of_Brazil.svg",
        "clubLogo": "Liverpool_FC.svg",
        "leagueLogo": "Premier_League_Logo.svg"
    },
    {
        "id": "p_4",
        "name": "Jan Oblak",
        "category": "Goalkeepers (GK)",
        "basePrice": "\u20b95M",
        "nation": "SLOVENIA",
        "flagImg": "Flag_of_Slovenia.svg",
        "pos": "GK",
        "rating": 88,
        "club": "ATLETICO MADRID",
        "clubImg": "Atletico_Madrid_Logo_2024.svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Jan Oblak.png",
        "image": "Jan Oblak.jpeg",
        "noBgImage": "no_bg/Jan Oblak.png",
        "flag": "Flag_of_Slovenia.svg",
        "clubLogo": "Atletico_Madrid_Logo_2024.svg",
        "leagueLogo": "LaLiga_EA_Sports_2023_Vertical_Logo.svg"
    },
    {
        "id": "p_5",
        "name": "Mike Maignan",
        "category": "Goalkeepers (GK)",
        "basePrice": "\u20b93M",
        "nation": "FRANCE",
        "flagImg": "Flag_of_France.svg",
        "pos": "GK",
        "rating": 87,
        "club": "AC MILAN",
        "clubImg": "AC_Milan_logo.svg",
        "league": "SERIE A",
        "leagueImg": "Serie_A_ENILIVE_logo.svg",
        "cardImg": "no_bg/Mike Maignan.png",
        "image": "Mike Maignan.jpeg",
        "noBgImage": "no_bg/Mike Maignan.png",
        "flag": "Flag_of_France.svg",
        "clubLogo": "AC_Milan_logo.svg",
        "leagueLogo": "Serie_A_ENILIVE_logo.svg"
    },
    {
        "id": "p_6",
        "name": "David Raya",
        "category": "Goalkeepers (GK)",
        "basePrice": "\u20b93M",
        "nation": "SPAIN",
        "flagImg": "Flag_of_the_Kingdom_of_Spain.svg",
        "pos": "GK",
        "rating": 87,
        "club": "ARSENAL",
        "clubImg": "Arsenal_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/David Raya.png",
        "image": "David Raya.jpeg",
        "noBgImage": "no_bg/David Raya.png",
        "flag": "Flag_of_the_Kingdom_of_Spain.svg",
        "clubLogo": "Arsenal_FC.svg",
        "leagueLogo": "Premier_League_Logo.svg"
    },
    {
        "id": "p_7",
        "name": "Virgil Van Dijk",
        "category": "Centre Backs (CB)",
        "basePrice": "\u20b910M",
        "nation": "NETHERLANDS",
        "flagImg": "Flag_of_the_Netherlands.svg",
        "pos": "CB",
        "rating": 90,
        "club": "LIVERPOOL",
        "clubImg": "Liverpool_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Virgil Van Dijk.png",
        "image": "Virgil Van Dijk.jpeg",
        "noBgImage": "no_bg/Virgil Van Dijk.png",
        "flag": "Flag_of_the_Netherlands.svg",
        "clubLogo": "Liverpool_FC.svg",
        "leagueLogo": "Premier_League_Logo.svg"
    },
    {
        "id": "p_8",
        "name": "William Saliba",
        "category": "Centre Backs (CB)",
        "basePrice": "\u20b97.5M",
        "nation": "FRANCE",
        "flagImg": "Flag_of_France.svg",
        "pos": "CB",
        "rating": 87,
        "club": "ARSENAL",
        "clubImg": "Arsenal_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/William Saliba.png",
        "image": "William Saliba.jpeg",
        "noBgImage": "no_bg/William Saliba.png",
        "flag": "Flag_of_France.svg",
        "clubLogo": "Arsenal_FC.svg",
        "leagueLogo": "Premier_League_Logo.svg"
    },
    {
        "id": "p_9",
        "name": "Gabriel",
        "category": "Centre Backs (CB)",
        "basePrice": "\u20b97.5M",
        "nation": "BRAZIL",
        "flagImg": "Flag_of_Brazil.svg",
        "pos": "CB",
        "rating": 88,
        "club": "ARSENAL",
        "clubImg": "Arsenal_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Gabriel.png",
        "image": "Gabriel.jpeg",
        "noBgImage": "no_bg/Gabriel.png",
        "flag": "Flag_of_Brazil.svg",
        "clubLogo": "Arsenal_FC.svg",
        "leagueLogo": "Premier_League_Logo.svg"
    },
    {
        "id": "p_10",
        "name": "Alessandro Bastoni",
        "category": "Centre Backs (CB)",
        "basePrice": "\u20b97.5M",
        "nation": "ITALY",
        "flagImg": "Flag_of_Italy.svg",
        "pos": "CB",
        "rating": 87,
        "club": "INTER MILAN",
        "clubImg": "FC_Internazionale_Milano_2021.svg",
        "league": "SERIE A",
        "leagueImg": "Serie_A_ENILIVE_logo.svg",
        "cardImg": "no_bg/Bastoni.png",
        "image": "Bastoni.jpeg",
        "noBgImage": "no_bg/Bastoni.png",
        "flag": "Flag_of_Italy.svg",
        "clubLogo": "FC_Internazionale_Milano_2021.svg",
        "leagueLogo": "Serie_A_ENILIVE_logo.svg"
    },
    {
        "id": "p_11",
        "name": "Ruben Dias",
        "category": "Centre Backs (CB)",
        "basePrice": "\u20b95M",
        "nation": "PORTUGAL",
        "flagImg": "Flag_of_Portugal_(official).svg",
        "pos": "CB",
        "rating": 86,
        "club": "MANCHESTER CITY",
        "clubImg": "Manchester_City_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Ruben Dias.png",
        "image": "Ruben Dias.jpeg",
        "noBgImage": "no_bg/Ruben Dias.png",
        "flag": "Flag_of_Portugal_(official).svg",
        "clubLogo": "Manchester_City_FC.svg",
        "leagueLogo": "Premier_League_Logo.svg"
    },
    {
        "id": "p_12",
        "name": "Marquinhos",
        "category": "Centre Backs (CB)",
        "basePrice": "\u20b97.5M",
        "nation": "BRAZIL",
        "flagImg": "Flag_of_Brazil.svg",
        "pos": "CB",
        "rating": 87,
        "club": "PSG",
        "clubImg": "PSG_logo.svg",
        "league": "LIGUE 1",
        "leagueImg": "Logo_Ligue_1_McDonald_s_2024.svg",
        "cardImg": "no_bg/Marquinhos .png",
        "image": "Marquinhos .jpeg",
        "noBgImage": "no_bg/Marquinhos .png",
        "flag": "Flag_of_Brazil.svg",
        "clubLogo": "PSG_logo.svg",
        "leagueLogo": "Logo_Ligue_1_McDonald_s_2024.svg"
    },
    {
        "id": "p_13",
        "name": "Ibrahima Konate",
        "category": "Centre Backs (CB)",
        "basePrice": "\u20b95M",
        "nation": "FRANCE",
        "flagImg": "Flag_of_France.svg",
        "pos": "CB",
        "rating": 86,
        "club": "LIVERPOOL",
        "clubImg": "Liverpool_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Ibrahim Konate.png",
        "image": "Ibrahim Konate.jpeg",
        "noBgImage": "no_bg/Ibrahim Konate.png",
        "flag": "Flag_of_France.svg",
        "clubLogo": "Liverpool_FC.svg",
        "leagueLogo": "Premier_League_Logo.svg"
    },
    {
        "id": "p_14",
        "name": "Antonio Rudiger",
        "category": "Centre Backs (CB)",
        "basePrice": "\u20b95M",
        "nation": "GERMANY",
        "flagImg": "Flag_of_Germany.svg",
        "pos": "CB",
        "rating": 86,
        "club": "REAL MADRID",
        "clubImg": "Real_Madrid_logo.svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Rudiger.png",
        "image": "Rudiger.jpeg",
        "noBgImage": "no_bg/Rudiger.png",
        "flag": "Flag_of_Germany.svg",
        "clubLogo": "Real_Madrid_logo.svg",
        "leagueLogo": "LaLiga_EA_Sports_2023_Vertical_Logo.svg"
    },
    {
        "id": "p_15",
        "name": "Dayot Upamecano",
        "category": "Centre Backs (CB)",
        "basePrice": "\u20b95M",
        "nation": "FRANCE",
        "flagImg": "Flag_of_France.svg",
        "pos": "CB",
        "rating": 85,
        "club": "BAYERN",
        "clubImg": "FC_Bayern_Munchen_logo.svg",
        "league": "BUNDESLIGA",
        "leagueImg": "Bundesliga_logo_(2017).svg",
        "cardImg": "no_bg/Dayot Upamecano.png",
        "image": "Dayot Upamecano.jpeg",
        "noBgImage": "no_bg/Dayot Upamecano.png",
        "flag": "Flag_of_France.svg",
        "clubLogo": "FC_Bayern_Munchen_logo.svg",
        "leagueLogo": "Bundesliga_logo_(2017).svg"
    },
    {
        "id": "p_16",
        "name": "Ronald Araujo",
        "category": "Centre Backs (CB)",
        "basePrice": "\u20b93M",
        "nation": "URUGUAY",
        "flagImg": "Flag_of_Uruguay.svg",
        "pos": "CB",
        "rating": 83,
        "club": "BARCELONA",
        "clubImg": "FC_Barcelona_(crest).svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Ronald Araujo.png",
        "image": "Ronald Araujo.jpeg",
        "noBgImage": "no_bg/Ronald Araujo.png",
        "flag": "Flag_of_Uruguay.svg",
        "clubLogo": "FC_Barcelona_(crest).svg",
        "leagueLogo": "LaLiga_EA_Sports_2023_Vertical_Logo.svg"
    },
    {
        "id": "p_17",
        "name": "Jonathan Tah",
        "category": "Centre Backs (CB)",
        "basePrice": "\u20b97.5M",
        "nation": "GERMANY",
        "flagImg": "Flag_of_Germany.svg",
        "pos": "CB",
        "rating": 87,
        "club": "BAYERN",
        "clubImg": "FC_Bayern_Munchen_logo.svg",
        "league": "BUNDESLIGA",
        "leagueImg": "Bundesliga_logo_(2017).svg",
        "cardImg": "no_bg/Jonnathan Tah.png",
        "image": "Jonnathan Tah.jpeg",
        "noBgImage": "no_bg/Jonnathan Tah.png",
        "flag": "Flag_of_Germany.svg",
        "clubLogo": "FC_Bayern_Munchen_logo.svg",
        "leagueLogo": "Bundesliga_logo_(2017).svg"
    },
    {
        "id": "p_18",
        "name": "William Pacho",
        "category": "Centre Backs (CB)",
        "basePrice": "\u20b95M",
        "nation": "ECUADOR",
        "flagImg": "Flag_of_Ecuador.svg",
        "pos": "CB",
        "rating": 86,
        "club": "PSG",
        "clubImg": "PSG_logo.svg",
        "league": "LIGUE 1",
        "leagueImg": "Logo_Ligue_1_McDonald_s_2024.svg",
        "cardImg": "no_bg/William Pacho.png",
        "image": "William Pacho.jpeg",
        "noBgImage": "no_bg/William Pacho.png",
        "flag": "Flag_of_Ecuador.svg",
        "clubLogo": "PSG_logo.svg",
        "leagueLogo": "Logo_Ligue_1_McDonald_s_2024.svg"
    },
    {
        "id": "p_19",
        "name": "Nico Schlotterbeck",
        "category": "Centre Backs (CB)",
        "basePrice": "\u20b95M",
        "nation": "GERMANY",
        "flagImg": "Flag_of_Germany.svg",
        "pos": "CB",
        "rating": 85,
        "club": "DORTMUND",
        "clubImg": "Borussia_Dortmund_logo.svg",
        "league": "BUNDESLIGA",
        "leagueImg": "Bundesliga_logo_(2017).svg",
        "cardImg": "no_bg/Schlotterbeck.png",
        "image": "Schlotterbeck.jpeg",
        "noBgImage": "no_bg/Schlotterbeck.png",
        "flag": "Flag_of_Germany.svg",
        "clubLogo": "Borussia_Dortmund_logo.svg",
        "leagueLogo": "Bundesliga_logo_(2017).svg"
    },
    {
        "id": "p_20",
        "name": "Bremer",
        "category": "Centre Backs (CB)",
        "basePrice": "\u20b95M",
        "nation": "BRAZIL",
        "flagImg": "Flag_of_Brazil.svg",
        "pos": "CB",
        "rating": 85,
        "club": "JUVENTUS",
        "clubImg": "Juventus_FC_logo.svg",
        "league": "SERIE A",
        "leagueImg": "Serie_A_ENILIVE_logo.svg",
        "cardImg": "no_bg/Bremer .png",
        "image": "Bremer .jpeg",
        "noBgImage": "no_bg/Bremer .png",
        "flag": "Flag_of_Brazil.svg",
        "clubLogo": "Juventus_FC_logo.svg",
        "leagueLogo": "Serie_A_ENILIVE_logo.svg"
    },
    {
        "id": "p_21",
        "name": "Eder Militao",
        "category": "Centre Backs (CB)",
        "basePrice": "\u20b95M",
        "nation": "BRAZIL",
        "flagImg": "Flag_of_Brazil.svg",
        "pos": "CB",
        "rating": 84,
        "club": "REAL MADRID",
        "clubImg": "Real_Madrid_logo.svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Eder Militao.png",
        "image": "Eder Militao.jpeg",
        "noBgImage": "no_bg/Eder Militao.png",
        "flag": "Flag_of_Brazil.svg",
        "clubLogo": "Real_Madrid_logo.svg",
        "leagueLogo": "LaLiga_EA_Sports_2023_Vertical_Logo.svg"
    },
    {
        "id": "p_22",
        "name": "Achraf Hakimi",
        "category": "Right Backs (RB)",
        "basePrice": "\u20b97.5M",
        "nation": "MOROCCO",
        "flagImg": "Flag_of_Morocco.svg",
        "pos": "RB",
        "rating": 89,
        "club": "PSG",
        "clubImg": "PSG_logo.svg",
        "league": "LIGUE 1",
        "leagueImg": "Logo_Ligue_1_McDonald_s_2024.svg",
        "cardImg": "no_bg/Achraf Hakimi.png",
        "image": "Achraf Hakimi.jpeg",
        "noBgImage": "no_bg/Achraf Hakimi.png",
        "flag": "Flag_of_Morocco.svg",
        "clubLogo": "PSG_logo.svg",
        "leagueLogo": "Logo_Ligue_1_McDonald_s_2024.svg"
    },
    {
        "id": "p_23",
        "name": "Trent Alexander-Arnold",
        "category": "Right Backs (RB)",
        "basePrice": "\u20b95M",
        "nation": "ENGLAND",
        "flagImg": "Flag_of_England.svg",
        "pos": "RB",
        "rating": 86,
        "club": "REAL MADRID",
        "clubImg": "Real_Madrid_logo.svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Trent Alexander Arnorld.png",
        "image": "Trent Alexander Arnorld.jpeg",
        "noBgImage": "no_bg/Trent Alexander Arnorld.png",
        "flag": "Flag_of_England.svg",
        "clubLogo": "Real_Madrid_logo.svg",
        "leagueLogo": "LaLiga_EA_Sports_2023_Vertical_Logo.svg"
    },
    {
        "id": "p_24",
        "name": "Jules Kounde",
        "category": "Right Backs (RB)",
        "basePrice": "\u20b95M",
        "nation": "FRANCE",
        "flagImg": "Flag_of_France.svg",
        "pos": "RB",
        "rating": 87,
        "club": "BARCELONA",
        "clubImg": "FC_Barcelona_(crest).svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Kounde.png",
        "image": "Kounde.jpeg",
        "noBgImage": "no_bg/Kounde.png",
        "flag": "Flag_of_France.svg",
        "clubLogo": "FC_Barcelona_(crest).svg",
        "leagueLogo": "LaLiga_EA_Sports_2023_Vertical_Logo.svg"
    },
    {
        "id": "p_25",
        "name": "Jeremie Frimpong",
        "category": "Right Backs (RB)",
        "basePrice": "\u20b95M",
        "nation": "NETHERLANDS",
        "flagImg": "Flag_of_the_Netherlands.svg",
        "pos": "RB",
        "rating": 83,
        "club": "LIVERPOOL",
        "clubImg": "Liverpool_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Jeremie Frimpong.png",
        "image": "Jeremie Frimpong.jpeg",
        "noBgImage": "no_bg/Jeremie Frimpong.png",
        "flag": "Flag_of_the_Netherlands.svg",
        "clubLogo": "Liverpool_FC.svg",
        "leagueLogo": "Premier_League_Logo.svg"
    },
    {
        "id": "p_26",
        "name": "Denzel Dumfries",
        "category": "Right Backs (RB)",
        "basePrice": "\u20b93M",
        "nation": "NETHERLANDS",
        "flagImg": "Flag_of_the_Netherlands.svg",
        "pos": "RB",
        "rating": 84,
        "club": "INTER MILAN",
        "clubImg": "FC_Internazionale_Milano_2021.svg",
        "league": "SERIE A",
        "leagueImg": "Serie_A_ENILIVE_logo.svg",
        "cardImg": "no_bg/Denzel Dumfries.png",
        "image": "Denzel Dumfries.jpeg",
        "noBgImage": "no_bg/Denzel Dumfries.png",
        "flag": "Flag_of_the_Netherlands.svg",
        "clubLogo": "FC_Internazionale_Milano_2021.svg",
        "leagueLogo": "Serie_A_ENILIVE_logo.svg"
    },
    {
        "id": "p_27",
        "name": "Marcos Llorente",
        "category": "Right Backs (RB)",
        "basePrice": "\u20b93M",
        "nation": "SPAIN",
        "flagImg": "Flag_of_the_Kingdom_of_Spain.svg",
        "pos": "RB",
        "rating": 84,
        "club": "ATLETICO MADRID",
        "clubImg": "Atletico_Madrid_Logo_2024.svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Marcos Llorente.png",
        "image": "Marcos Llorente.jpeg",
        "noBgImage": "no_bg/Marcos Llorente.png",
        "flag": "Flag_of_the_Kingdom_of_Spain.svg",
        "clubLogo": "Atletico_Madrid_Logo_2024.svg",
        "leagueLogo": "LaLiga_EA_Sports_2023_Vertical_Logo.svg"
    },
    {
        "id": "p_28",
        "name": "Nuno Mendes",
        "category": "Left Backs (LB)",
        "basePrice": "\u20b97.5M",
        "nation": "PORTUGAL",
        "flagImg": "Flag_of_Portugal_(official).svg",
        "pos": "LB",
        "rating": 86,
        "club": "PSG",
        "clubImg": "PSG_logo.svg",
        "league": "LIGUE 1",
        "leagueImg": "Logo_Ligue_1_McDonald_s_2024.svg",
        "cardImg": "no_bg/Nuno Mendes.png",
        "image": "Nuno Mendes.jpeg",
        "noBgImage": "no_bg/Nuno Mendes.png",
        "flag": "Flag_of_Portugal_(official).svg",
        "clubLogo": "PSG_logo.svg",
        "leagueLogo": "Logo_Ligue_1_McDonald_s_2024.svg"
    },
    {
        "id": "p_29",
        "name": "Josko Gvardiol",
        "category": "Left Backs (LB)",
        "basePrice": "\u20b95M",
        "nation": "CROATIA",
        "flagImg": "Flag_of_Croatia.svg",
        "pos": "LB",
        "rating": 84,
        "club": "MANCHESTER CITY",
        "clubImg": "Manchester_City_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Gvardiol.png",
        "image": "Gvardiol.jpeg",
        "noBgImage": "no_bg/Gvardiol.png",
        "flag": "Flag_of_Croatia.svg",
        "clubLogo": "Manchester_City_FC.svg",
        "leagueLogo": "Premier_League_Logo.svg"
    },
    {
        "id": "p_30",
        "name": "Alphonso Davies",
        "category": "Left Backs (LB)",
        "basePrice": "\u20b95M",
        "nation": "CANADA",
        "flagImg": "Flag_of_Canada_(Pantone).svg",
        "pos": "LB",
        "rating": 84,
        "club": "BAYERN",
        "clubImg": "FC_Bayern_Munchen_logo.svg",
        "league": "BUNDESLIGA",
        "leagueImg": "Bundesliga_logo_(2017).svg",
        "cardImg": "no_bg/Alphonso Davies.png",
        "image": "Alphonso Davies.jpeg",
        "noBgImage": "no_bg/Alphonso Davies.png",
        "flag": "Flag_of_Canada_(Pantone).svg",
        "clubLogo": "FC_Bayern_Munchen_logo.svg",
        "leagueLogo": "Bundesliga_logo_(2017).svg"
    },
    {
        "id": "p_31",
        "name": "Theo Hernandez",
        "category": "Left Backs (LB)",
        "basePrice": "\u20b95M",
        "nation": "FRANCE",
        "flagImg": "Flag_of_France.svg",
        "pos": "LB",
        "rating": 84,
        "club": "AL HILAL",
        "clubImg": "Al_Hilal_SFC_Logo.svg",
        "league": "SAUDI PRO LEAGUE",
        "leagueImg": "Roshn_Saudi_League_Logo.svg",
        "cardImg": "no_bg/Theo Hernandez.png",
        "image": "Theo Hernandez.jpeg",
        "noBgImage": "no_bg/Theo Hernandez.png",
        "flag": "Flag_of_France.svg",
        "clubLogo": "Al_Hilal_SFC_Logo.svg",
        "leagueLogo": "Roshn_Saudi_League_Logo.svg"
    },
    {
        "id": "p_32",
        "name": "Marc Cucurella",
        "category": "Left Backs (LB)",
        "basePrice": "\u20b95M",
        "nation": "SPAIN",
        "flagImg": "Flag_of_the_Kingdom_of_Spain.svg",
        "pos": "LB",
        "rating": 84,
        "club": "CHELSEA",
        "clubImg": "Chelsea_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Marc Cucurella.png",
        "image": "Marc Cucurella.jpeg",
        "noBgImage": "no_bg/Marc Cucurella.png",
        "flag": "Flag_of_the_Kingdom_of_Spain.svg",
        "clubLogo": "Chelsea_FC.svg",
        "leagueLogo": "Premier_League_Logo.svg"
    },
    {
        "id": "p_33",
        "name": "Balde",
        "category": "Left Backs (LB)",
        "basePrice": "\u20b93M",
        "nation": "SPAIN",
        "flagImg": "Flag_of_the_Kingdom_of_Spain.svg",
        "pos": "LB",
        "rating": 83,
        "club": "BARCELONA",
        "clubImg": "FC_Barcelona_(crest).svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Balde.png",
        "image": "Balde.jpeg",
        "noBgImage": "no_bg/Balde.png",
        "flag": "Flag_of_the_Kingdom_of_Spain.svg",
        "clubLogo": "FC_Barcelona_(crest).svg",
        "leagueLogo": "LaLiga_EA_Sports_2023_Vertical_Logo.svg"
    },
    {
        "id": "p_34",
        "name": "Rodri",
        "category": "Defensive Midfielders (CDM)",
        "basePrice": "\u20b910M",
        "nation": "SPAIN",
        "flagImg": "Flag_of_the_Kingdom_of_Spain.svg",
        "pos": "CDM",
        "rating": 90,
        "club": "MANCHESTER CITY",
        "clubImg": "Manchester_City_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Rodri.png",
        "image": "Rodri.jpeg",
        "noBgImage": "no_bg/Rodri.png",
        "flag": "Flag_of_the_Kingdom_of_Spain.svg",
        "clubLogo": "Manchester_City_FC.svg",
        "leagueLogo": "Premier_League_Logo.svg"
    },
    {
        "id": "p_35",
        "name": "Kimmich",
        "category": "Defensive Midfielders (CDM)",
        "basePrice": "\u20b97.5M",
        "nation": "GERMANY",
        "flagImg": "Flag_of_Germany.svg",
        "pos": "CDM",
        "rating": 89,
        "club": "BAYERN",
        "clubImg": "FC_Bayern_Munchen_logo.svg",
        "league": "BUNDESLIGA",
        "leagueImg": "Bundesliga_logo_(2017).svg",
        "cardImg": "no_bg/Joshua Kimmich.png",
        "image": "Joshua Kimmich.jpeg",
        "noBgImage": "no_bg/Joshua Kimmich.png",
        "flag": "Flag_of_Germany.svg",
        "clubLogo": "FC_Bayern_Munchen_logo.svg",
        "leagueLogo": "Bundesliga_logo_(2017).svg"
    },
    {
        "id": "p_36",
        "name": "Declan Rice",
        "category": "Defensive Midfielders (CDM)",
        "basePrice": "\u20b97.5M",
        "nation": "ENGLAND",
        "flagImg": "Flag_of_England.svg",
        "pos": "CDM",
        "rating": 87,
        "club": "ARSENAL",
        "clubImg": "Arsenal_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Rice.png",
        "image": "Rice.jpeg",
        "noBgImage": "no_bg/Rice.png",
        "flag": "Flag_of_England.svg",
        "clubLogo": "Arsenal_FC.svg",
        "leagueLogo": "Premier_League_Logo.svg"
    },
    {
        "id": "p_37",
        "name": "Moises Caicedo",
        "category": "Defensive Midfielders (CDM)",
        "basePrice": "\u20b97.5M",
        "nation": "ECUADOR",
        "flagImg": "Flag_of_Ecuador.svg",
        "pos": "CDM",
        "rating": 87,
        "club": "CHELSEA",
        "clubImg": "Chelsea_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Caicedo.png",
        "image": "Caicedo.jpeg",
        "noBgImage": "no_bg/Caicedo.png",
        "flag": "Flag_of_Ecuador.svg",
        "clubLogo": "Chelsea_FC.svg",
        "leagueLogo": "Premier_League_Logo.svg"
    },
    {
        "id": "p_38",
        "name": "Sandro Tonali",
        "category": "Defensive Midfielders (CDM)",
        "basePrice": "\u20b95M",
        "nation": "ITALY",
        "flagImg": "Flag_of_Italy.svg",
        "pos": "CDM",
        "rating": 86,
        "club": "NEWCASTLE",
        "clubImg": "Newcastle_United_logo.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Tonali.png",
        "image": "Tonali.jpeg",
        "noBgImage": "no_bg/Tonali.png",
        "flag": "Flag_of_Italy.svg",
        "clubLogo": "Newcastle_United_logo.svg",
        "leagueLogo": "Premier_League_Logo.svg"
    },
    {
        "id": "p_39",
        "name": "Ryan Gravenberch",
        "category": "Defensive Midfielders (CDM)",
        "basePrice": "\u20b95M",
        "nation": "NETHERLANDS",
        "flagImg": "Flag_of_the_Netherlands.svg",
        "pos": "CDM",
        "rating": 85,
        "club": "LIVERPOOL",
        "clubImg": "Liverpool_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Gravenberch.png",
        "image": "Gravenberch.jpeg",
        "noBgImage": "no_bg/Gravenberch.png",
        "flag": "Flag_of_the_Netherlands.svg",
        "clubLogo": "Liverpool_FC.svg",
        "leagueLogo": "Premier_League_Logo.svg"
    },
    {
        "id": "p_40",
        "name": "Pedri",
        "category": "Central Midfielders (CM)",
        "basePrice": "\u20b97.5M",
        "nation": "SPAIN",
        "flagImg": "Flag_of_the_Kingdom_of_Spain.svg",
        "pos": "CM",
        "rating": 89,
        "club": "BARCELONA",
        "clubImg": "FC_Barcelona_(crest).svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Pedri.png",
        "image": "Pedri.jpeg",
        "noBgImage": "no_bg/Pedri.png",
        "flag": "Flag_of_the_Kingdom_of_Spain.svg",
        "clubLogo": "FC_Barcelona_(crest).svg",
        "leagueLogo": "LaLiga_EA_Sports_2023_Vertical_Logo.svg"
    },
    {
        "id": "p_41",
        "name": "Kevin De Bruyne",
        "category": "Central Midfielders (CM)",
        "basePrice": "\u20b97.5M",
        "nation": "BELGIUM",
        "flagImg": "Flag_of_Belgium.svg",
        "pos": "CM",
        "rating": 87,
        "club": "NAPOLI",
        "clubImg": "SSC_Napoli_logo.svg",
        "league": "SERIE A",
        "leagueImg": "Serie_A_ENILIVE_logo.svg",
        "cardImg": "no_bg/Kevin De Bruyne.png",
        "image": "Kevin De Bruyne.jpeg",
        "noBgImage": "no_bg/Kevin De Bruyne.png",
        "flag": "Flag_of_Belgium.svg",
        "clubLogo": "SSC_Napoli_logo.svg",
        "leagueLogo": "Serie_A_ENILIVE_logo.svg"
    },
    {
        "id": "p_42",
        "name": "Federico Valverde",
        "category": "Central Midfielders (CM)",
        "basePrice": "\u20b910M",
        "nation": "URUGUAY",
        "flagImg": "Flag_of_Uruguay.svg",
        "pos": "CM",
        "rating": 89,
        "club": "REAL MADRID",
        "clubImg": "Real_Madrid_logo.svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Frederico Valverde.png",
        "image": "Frederico Valverde.jpeg",
        "noBgImage": "no_bg/Frederico Valverde.png",
        "flag": "Flag_of_Uruguay.svg",
        "clubLogo": "Real_Madrid_logo.svg",
        "leagueLogo": "LaLiga_EA_Sports_2023_Vertical_Logo.svg"
    },
    {
        "id": "p_43",
        "name": "Martin Odegaard",
        "category": "Central Midfielders (CM)",
        "basePrice": "\u20b97.5M",
        "nation": "NORWAY",
        "flagImg": "Flag_of_Norway.svg",
        "pos": "CM",
        "rating": 87,
        "club": "ARSENAL",
        "clubImg": "Arsenal_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Martin Odegard.png",
        "image": "Martin Odegard.jpeg",
        "noBgImage": "no_bg/Martin Odegard.png",
        "flag": "Flag_of_Norway.svg",
        "clubLogo": "Arsenal_FC.svg",
        "leagueLogo": "Premier_League_Logo.svg"
    },
    {
        "id": "p_44",
        "name": "Bernardo Silva",
        "category": "Central Midfielders (CM)",
        "basePrice": "\u20b93M",
        "nation": "PORTUGAL",
        "flagImg": "Flag_of_Portugal_(official).svg",
        "pos": "CM",
        "rating": 84,
        "club": "MANCHESTER CITY",
        "clubImg": "Manchester_City_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Bernardo Silva.png",
        "image": "Bernardo Silva.jpeg",
        "noBgImage": "no_bg/Bernardo Silva.png",
        "flag": "Flag_of_Portugal_(official).svg",
        "clubLogo": "Manchester_City_FC.svg",
        "leagueLogo": "Premier_League_Logo.svg"
    },
    {
        "id": "p_45",
        "name": "Vitinha",
        "category": "Central Midfielders (CM)",
        "basePrice": "\u20b97.5M",
        "nation": "PORTUGAL",
        "flagImg": "Flag_of_Portugal_(official).svg",
        "pos": "CM",
        "rating": 89,
        "club": "PSG",
        "clubImg": "PSG_logo.svg",
        "league": "LIGUE 1",
        "leagueImg": "Logo_Ligue_1_McDonald_s_2024.svg",
        "cardImg": "no_bg/Vitinha.png",
        "image": "Vitinha.jpeg",
        "noBgImage": "no_bg/Vitinha.png",
        "flag": "Flag_of_Portugal_(official).svg",
        "clubLogo": "PSG_logo.svg",
        "leagueLogo": "Logo_Ligue_1_McDonald_s_2024.svg"
    },
    {
        "id": "p_46",
        "name": "Frenkie De Jong",
        "category": "Central Midfielders (CM)",
        "basePrice": "\u20b97.5M",
        "nation": "NETHERLANDS",
        "flagImg": "Flag_of_the_Netherlands.svg",
        "pos": "CM",
        "rating": 87,
        "club": "BARCELONA",
        "clubImg": "FC_Barcelona_(crest).svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Frankie De Jong.png",
        "image": "Frankie De Jong.jpeg",
        "noBgImage": "no_bg/Frankie De Jong.png",
        "flag": "Flag_of_the_Netherlands.svg",
        "clubLogo": "FC_Barcelona_(crest).svg",
        "leagueLogo": "LaLiga_EA_Sports_2023_Vertical_Logo.svg"
    },
    {
        "id": "p_47",
        "name": "Nicolo Barella",
        "category": "Central Midfielders (CM)",
        "basePrice": "\u20b97.5M",
        "nation": "ITALY",
        "flagImg": "Flag_of_Italy.svg",
        "pos": "CM",
        "rating": 87,
        "club": "INTER MILAN",
        "clubImg": "FC_Internazionale_Milano_2021.svg",
        "league": "SERIE A",
        "leagueImg": "Serie_A_ENILIVE_logo.svg",
        "cardImg": "no_bg/Nicolo Barella.png",
        "image": "Nicolo Barella.jpeg",
        "noBgImage": "no_bg/Nicolo Barella.png",
        "flag": "Flag_of_Italy.svg",
        "clubLogo": "FC_Internazionale_Milano_2021.svg",
        "leagueLogo": "Serie_A_ENILIVE_logo.svg"
    },
    {
        "id": "p_48",
        "name": "Bruno Guimaraes",
        "category": "Central Midfielders (CM)",
        "basePrice": "\u20b95M",
        "nation": "BRAZIL",
        "flagImg": "Flag_of_Brazil.svg",
        "pos": "CM",
        "rating": 86,
        "club": "NEWCASTLE",
        "clubImg": "Newcastle_United_logo.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Bruno Guimaraes.png",
        "image": "Bruno Guimaraes.jpeg",
        "noBgImage": "no_bg/Bruno Guimaraes.png",
        "flag": "Flag_of_Brazil.svg",
        "clubLogo": "Newcastle_United_logo.svg",
        "leagueLogo": "Premier_League_Logo.svg"
    },
    {
        "id": "p_49",
        "name": "Joao Neves",
        "category": "Central Midfielders (CM)",
        "basePrice": "\u20b95M",
        "nation": "PORTUGAL",
        "flagImg": "Flag_of_Portugal_(official).svg",
        "pos": "CM",
        "rating": 85,
        "club": "PSG",
        "clubImg": "PSG_logo.svg",
        "league": "LIGUE 1",
        "leagueImg": "Logo_Ligue_1_McDonald_s_2024.svg",
        "cardImg": "no_bg/Joao Neves.png",
        "image": "Joao Neves.jpeg",
        "noBgImage": "no_bg/Joao Neves.png",
        "flag": "Flag_of_Portugal_(official).svg",
        "clubLogo": "PSG_logo.svg",
        "leagueLogo": "Logo_Ligue_1_McDonald_s_2024.svg"
    },
    {
        "id": "p_50",
        "name": "Alexis Mac Allister",
        "category": "Central Midfielders (CM)",
        "basePrice": "\u20b93M",
        "nation": "ARGENTINA",
        "flagImg": "Flag_of_Argentina.svg",
        "pos": "CM",
        "rating": 87,
        "club": "LIVERPOOL",
        "clubImg": "Liverpool_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Alexis Mac Allister.png",
        "image": "Alexis Mac Allister.jpeg",
        "noBgImage": "no_bg/Alexis Mac Allister.png",
        "flag": "Flag_of_Argentina.svg",
        "clubLogo": "Liverpool_FC.svg",
        "leagueLogo": "Premier_League_Logo.svg"
    },
    {
        "id": "p_51",
        "name": "Tijjani Reijnders",
        "category": "Central Midfielders (CM)",
        "basePrice": "\u20b95M",
        "nation": "NETHERLANDS",
        "flagImg": "Flag_of_the_Netherlands.svg",
        "pos": "CM",
        "rating": 86,
        "club": "MANCHESTER CITY",
        "clubImg": "Manchester_City_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Reijnders.png",
        "image": "Reijnders.jpeg",
        "noBgImage": "no_bg/Reijnders.png",
        "flag": "Flag_of_the_Netherlands.svg",
        "clubLogo": "Manchester_City_FC.svg",
        "leagueLogo": "Premier_League_Logo.svg"
    },
    {
        "id": "p_52",
        "name": "Enzo Fernandez",
        "category": "Central Midfielders (CM)",
        "basePrice": "\u20b95M",
        "nation": "ARGENTINA",
        "flagImg": "Flag_of_Argentina.svg",
        "pos": "CM",
        "rating": 84,
        "club": "CHELSEA",
        "clubImg": "Chelsea_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Enzo Fernandez.png",
        "image": "Enzo Fernandez.jpeg",
        "noBgImage": "no_bg/Enzo Fernandez.png",
        "flag": "Flag_of_Argentina.svg",
        "clubLogo": "Chelsea_FC.svg",
        "leagueLogo": "Premier_League_Logo.svg"
    },
    {
        "id": "p_53",
        "name": "Scott McTominay",
        "category": "Central Midfielders (CM)",
        "basePrice": "\u20b93M",
        "nation": "SCOTLAND",
        "flagImg": "Flag_of_Scotland.svg",
        "pos": "CM",
        "rating": 85,
        "club": "NAPOLI",
        "clubImg": "SSC_Napoli_logo.svg",
        "league": "SERIE A",
        "leagueImg": "Serie_A_ENILIVE_logo.svg",
        "cardImg": "no_bg/Scott Mctominay.png",
        "image": "Scott Mctominay.jpeg",
        "noBgImage": "no_bg/Scott Mctominay.png",
        "flag": "Flag_of_Scotland.svg",
        "clubLogo": "SSC_Napoli_logo.svg",
        "leagueLogo": "Serie_A_ENILIVE_logo.svg"
    },
    {
        "id": "p_54",
        "name": "Youri Tielemans",
        "category": "Central Midfielders (CM)",
        "basePrice": "\u20b93M",
        "nation": "BELGIUM",
        "flagImg": "Flag_of_Belgium.svg",
        "pos": "CM",
        "rating": 85,
        "club": "ASTON VILLA",
        "clubImg": "Aston_Villa_FC_logo.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Youri tielmans .png",
        "image": "Youri tielmans .jpeg",
        "noBgImage": "no_bg/Youri tielmans .png",
        "flag": "Flag_of_Belgium.svg",
        "clubLogo": "Aston_Villa_FC_logo.svg",
        "leagueLogo": "Premier_League_Logo.svg"
    },
    {
        "id": "p_55",
        "name": "Jude Bellingham",
        "category": "Attacking Midfielders (CAM)",
        "basePrice": "\u20b910M",
        "nation": "ENGLAND",
        "flagImg": "Flag_of_England.svg",
        "pos": "CAM",
        "rating": 90,
        "club": "REAL MADRID",
        "clubImg": "Real_Madrid_logo.svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Jude Bellingham.png",
        "image": "Jude Bellingham.jpeg",
        "noBgImage": "no_bg/Jude Bellingham.png",
        "flag": "Flag_of_England.svg",
        "clubLogo": "Real_Madrid_logo.svg",
        "leagueLogo": "LaLiga_EA_Sports_2023_Vertical_Logo.svg"
    },
    {
        "id": "p_56",
        "name": "Florian Wirtz",
        "category": "Attacking Midfielders (CAM)",
        "basePrice": "\u20b97.5M",
        "nation": "GERMANY",
        "flagImg": "Flag_of_Germany.svg",
        "pos": "CAM",
        "rating": 89,
        "club": "LIVERPOOL",
        "clubImg": "Liverpool_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Florian Wirtz.png",
        "image": "Florian Wirtz.jpeg",
        "noBgImage": "no_bg/Florian Wirtz.png",
        "flag": "Flag_of_Germany.svg",
        "clubLogo": "Liverpool_FC.svg",
        "leagueLogo": "Premier_League_Logo.svg"
    },
    {
        "id": "p_57",
        "name": "Jamal Musiala",
        "category": "Attacking Midfielders (CAM)",
        "basePrice": "\u20b97.5M",
        "nation": "GERMANY",
        "flagImg": "Flag_of_Germany.svg",
        "pos": "CAM",
        "rating": 88,
        "club": "BAYERN",
        "clubImg": "FC_Bayern_Munchen_logo.svg",
        "league": "BUNDESLIGA",
        "leagueImg": "Bundesliga_logo_(2017).svg",
        "cardImg": "no_bg/Jamal Musiala.png",
        "image": "Jamal Musiala.jpeg",
        "noBgImage": "no_bg/Jamal Musiala.png",
        "flag": "Flag_of_Germany.svg",
        "clubLogo": "FC_Bayern_Munchen_logo.svg",
        "leagueLogo": "Bundesliga_logo_(2017).svg"
    },
    {
        "id": "p_58",
        "name": "Bruno Fernandes",
        "category": "Attacking Midfielders (CAM)",
        "basePrice": "\u20b97.5M",
        "nation": "PORTUGAL",
        "flagImg": "Flag_of_Portugal_(official).svg",
        "pos": "CAM",
        "rating": 87,
        "club": "MANCHESTER UNITED",
        "clubImg": "Manchester_United_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Bruno Fernandes.png",
        "image": "Bruno Fernandes.jpeg",
        "noBgImage": "no_bg/Bruno Fernandes.png",
        "flag": "Flag_of_Portugal_(official).svg",
        "clubLogo": "Manchester_United_FC.svg",
        "leagueLogo": "Premier_League_Logo.svg"
    },
    {
        "id": "p_59",
        "name": "Cole Palmer",
        "category": "Attacking Midfielders (CAM)",
        "basePrice": "\u20b97.5M",
        "nation": "ENGLAND",
        "flagImg": "Flag_of_England.svg",
        "pos": "CAM",
        "rating": 87,
        "club": "CHELSEA",
        "clubImg": "Chelsea_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Cole Palmer.png",
        "image": "Cole Palmer.jpeg",
        "noBgImage": "no_bg/Cole Palmer.png",
        "flag": "Flag_of_England.svg",
        "clubLogo": "Chelsea_FC.svg",
        "leagueLogo": "Premier_League_Logo.svg"
    },
    {
        "id": "p_60",
        "name": "Paulo Dybala",
        "category": "Attacking Midfielders (CAM)",
        "basePrice": "\u20b95M",
        "nation": "ARGENTINA",
        "flagImg": "Flag_of_Argentina.svg",
        "pos": "CAM",
        "rating": 86,
        "club": "ROMA",
        "clubImg": "AS_Roma_logo_(2017).svg",
        "league": "SERIE A",
        "leagueImg": "Serie_A_ENILIVE_logo.svg",
        "cardImg": "no_bg/Paulo Dybala.png",
        "image": "Paulo Dybala.jpeg",
        "noBgImage": "no_bg/Paulo Dybala.png",
        "flag": "Flag_of_Argentina.svg",
        "clubLogo": "AS_Roma_logo_(2017).svg",
        "leagueLogo": "Serie_A_ENILIVE_logo.svg"
    },
    {
        "id": "p_61",
        "name": "Vinicius Jr.",
        "category": "Left Wingers / Midfielders (LW/LM)",
        "basePrice": "\u20b910M",
        "nation": "BRAZIL",
        "flagImg": "Flag_of_Brazil.svg",
        "pos": "LW",
        "rating": 89,
        "club": "REAL MADRID",
        "clubImg": "Real_Madrid_logo.svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Vinicius Jr.png",
        "image": "Vinicius Jr.jpeg",
        "noBgImage": "no_bg/Vinicius Jr.png",
        "flag": "Flag_of_Brazil.svg",
        "clubLogo": "Real_Madrid_logo.svg",
        "leagueLogo": "LaLiga_EA_Sports_2023_Vertical_Logo.svg"
    },
    {
        "id": "p_62",
        "name": "Khvicha Kvaratskhelia",
        "category": "Left Wingers / Midfielders (LW/LM)",
        "basePrice": "\u20b97.5M",
        "nation": "GEORGIA",
        "flagImg": "Flag_of_Georgia.svg",
        "pos": "LW",
        "rating": 87,
        "club": "PSG",
        "clubImg": "PSG_logo.svg",
        "league": "LIGUE 1",
        "leagueImg": "Logo_Ligue_1_McDonald_s_2024.svg",
        "cardImg": "no_bg/Kvicha Kvaratskhelia.png",
        "image": "Kvicha Kvaratskhelia.jpeg",
        "noBgImage": "no_bg/Kvicha Kvaratskhelia.png",
        "flag": "Flag_of_Georgia.svg",
        "clubLogo": "PSG_logo.svg",
        "leagueLogo": "Logo_Ligue_1_McDonald_s_2024.svg"
    },
    {
        "id": "p_63",
        "name": "Raphinha",
        "category": "Left Wingers / Midfielders (LW/LM)",
        "basePrice": "\u20b97.5M",
        "nation": "BRAZIL",
        "flagImg": "Flag_of_Brazil.svg",
        "pos": "LW",
        "rating": 89,
        "club": "BARCELONA",
        "clubImg": "FC_Barcelona_(crest).svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Raphinha.png",
        "image": "Raphinha.jpeg",
        "noBgImage": "no_bg/Raphinha.png",
        "flag": "Flag_of_Brazil.svg",
        "clubLogo": "FC_Barcelona_(crest).svg",
        "leagueLogo": "LaLiga_EA_Sports_2023_Vertical_Logo.svg"
    },
    {
        "id": "p_64",
        "name": "Nico Williams",
        "category": "Left Wingers / Midfielders (LW/LM)",
        "basePrice": "\u20b95M",
        "nation": "SPAIN",
        "flagImg": "Flag_of_the_Kingdom_of_Spain.svg",
        "pos": "LW",
        "rating": 86,
        "club": "ATHLETIC BILBAO",
        "clubImg": "Club_Athletic_Bilbao_logo.svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Nico Williams.png",
        "image": "Nico Williams.jpeg",
        "noBgImage": "no_bg/Nico Williams.png",
        "flag": "Flag_of_the_Kingdom_of_Spain.svg",
        "clubLogo": "Club_Athletic_Bilbao_logo.svg",
        "leagueLogo": "LaLiga_EA_Sports_2023_Vertical_Logo.svg"
    },
    {
        "id": "p_65",
        "name": "Luis Diaz",
        "category": "Left Wingers / Midfielders (LW/LM)",
        "basePrice": "\u20b95M",
        "nation": "COLOMBIA",
        "flagImg": "Flag_of_Colombia.svg",
        "pos": "LW",
        "rating": 85,
        "club": "BAYERN",
        "clubImg": "FC_Bayern_Munchen_logo.svg",
        "league": "BUNDESLIGA",
        "leagueImg": "Bundesliga_logo_(2017).svg",
        "cardImg": "no_bg/Luis Diaz.png",
        "image": "Luis Diaz.jpeg",
        "noBgImage": "no_bg/Luis Diaz.png",
        "flag": "Flag_of_Colombia.svg",
        "clubLogo": "FC_Bayern_Munchen_logo.svg",
        "leagueLogo": "Bundesliga_logo_(2017).svg"
    },
    {
        "id": "p_66",
        "name": "Heung-Min Son",
        "category": "Left Wingers / Midfielders (LW/LM)",
        "basePrice": "\u20b95M",
        "nation": "SOUTH KOREA",
        "flagImg": "Flag_of_South_Korea.svg",
        "pos": "LW",
        "rating": 85,
        "club": "LAFC",
        "clubImg": "LAFC_logo.svg",
        "league": "MLS",
        "leagueImg": "Major_League_Soccer_logo.svg",
        "cardImg": "no_bg/Heung Min Son.png",
        "image": "Heung Min Son.jpeg",
        "noBgImage": "no_bg/Heung Min Son.png",
        "flag": "Flag_of_South_Korea.svg",
        "clubLogo": "LAFC_logo.svg",
        "leagueLogo": "Major_League_Soccer_logo.svg"
    },
    {
        "id": "p_67",
        "name": "Rafael Leao",
        "category": "Left Wingers / Midfielders (LW/LM)",
        "basePrice": "\u20b95M",
        "nation": "PORTUGAL",
        "flagImg": "Flag_of_Portugal_(official).svg",
        "pos": "LW",
        "rating": 84,
        "club": "AC MILAN",
        "clubImg": "AC_Milan_logo.svg",
        "league": "SERIE A",
        "leagueImg": "Serie_A_ENILIVE_logo.svg",
        "cardImg": "no_bg/Rafael Leao.png",
        "image": "Rafael Leao.jpeg",
        "noBgImage": "no_bg/Rafael Leao.png",
        "flag": "Flag_of_Portugal_(official).svg",
        "clubLogo": "AC_Milan_logo.svg",
        "leagueLogo": "Serie_A_ENILIVE_logo.svg"
    },
    {
        "id": "p_68",
        "name": "Bradley Barcola",
        "category": "Left Wingers / Midfielders (LW/LM)",
        "basePrice": "\u20b95M",
        "nation": "FRANCE",
        "flagImg": "Flag_of_France.svg",
        "pos": "LW",
        "rating": 84,
        "club": "PSG",
        "clubImg": "PSG_logo.svg",
        "league": "LIGUE 1",
        "leagueImg": "Logo_Ligue_1_McDonald_s_2024.svg",
        "cardImg": "no_bg/Bradley Barcola.png",
        "image": "Bradley Barcola.jpeg",
        "noBgImage": "no_bg/Bradley Barcola.png",
        "flag": "Flag_of_France.svg",
        "clubLogo": "PSG_logo.svg",
        "leagueLogo": "Logo_Ligue_1_McDonald_s_2024.svg"
    },
    {
        "id": "p_69",
        "name": "Cody Gakpo",
        "category": "Left Wingers / Midfielders (LW/LM)",
        "basePrice": "\u20b95M",
        "nation": "NETHERLANDS",
        "flagImg": "Flag_of_the_Netherlands.svg",
        "pos": "LW",
        "rating": 84,
        "club": "LIVERPOOL",
        "clubImg": "Liverpool_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Cody Gakpo.png",
        "image": "Cody Gakpo.jpeg",
        "noBgImage": "no_bg/Cody Gakpo.png",
        "flag": "Flag_of_the_Netherlands.svg",
        "clubLogo": "Liverpool_FC.svg",
        "leagueLogo": "Premier_League_Logo.svg"
    },
    {
        "id": "p_70",
        "name": "Kingsley Coman",
        "category": "Left Wingers / Midfielders (LW/LM)",
        "basePrice": "\u20b93M",
        "nation": "FRANCE",
        "flagImg": "Flag_of_France.svg",
        "pos": "LW",
        "rating": 83,
        "club": "AL NASSER",
        "clubImg": "Al_Nassr_FC_logo.svg",
        "league": "SAUDI PRO LEAGUE",
        "leagueImg": "Roshn_Saudi_League_Logo.svg",
        "cardImg": "no_bg/Kingsley Coman.png",
        "image": "Kingsley Coman.jpeg",
        "noBgImage": "no_bg/Kingsley Coman.png",
        "flag": "Flag_of_France.svg",
        "clubLogo": "Al_Nassr_FC_logo.svg",
        "leagueLogo": "Roshn_Saudi_League_Logo.svg"
    },
    {
        "id": "p_71",
        "name": "Gabriel Martinelli",
        "category": "Left Wingers / Midfielders (LW/LM)",
        "basePrice": "\u20b93M",
        "nation": "BRAZIL",
        "flagImg": "Flag_of_Brazil.svg",
        "pos": "LW",
        "rating": 81,
        "club": "ARSENAL",
        "clubImg": "Arsenal_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Gabriel Martinelli.png",
        "image": "Gabriel Martinelli.jpeg",
        "noBgImage": "no_bg/Gabriel Martinelli.png",
        "flag": "Flag_of_Brazil.svg",
        "clubLogo": "Arsenal_FC.svg",
        "leagueLogo": "Premier_League_Logo.svg"
    },
    {
        "id": "p_72",
        "name": "Anthony Gordon",
        "category": "Left Wingers / Midfielders (LW/LM)",
        "basePrice": "\u20b93M",
        "nation": "ENGLAND",
        "flagImg": "Flag_of_England.svg",
        "pos": "LW",
        "rating": 83,
        "club": "NEWCASTLE",
        "clubImg": "Newcastle_United_logo.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Anthony Gordon.png",
        "image": "Anthony Gordon.jpeg",
        "noBgImage": "no_bg/Anthony Gordon.png",
        "flag": "Flag_of_England.svg",
        "clubLogo": "Newcastle_United_logo.svg",
        "leagueLogo": "Premier_League_Logo.svg"
    },
    {
        "id": "p_73",
        "name": "Sadio Mane",
        "category": "Left Wingers / Midfielders (LW/LM)",
        "basePrice": "\u20b93M",
        "nation": "SENEGAL",
        "flagImg": "Flag_of_Senegal.svg",
        "pos": "LW",
        "rating": 83,
        "club": "AL NASSER",
        "clubImg": "Al_Nassr_FC_logo.svg",
        "league": "SAUDI PRO LEAGUE",
        "leagueImg": "Roshn_Saudi_League_Logo.svg",
        "cardImg": "no_bg/Sadio Mane.png",
        "image": "Sadio Mane.jpeg",
        "noBgImage": "no_bg/Sadio Mane.png",
        "flag": "Flag_of_Senegal.svg",
        "clubLogo": "Al_Nassr_FC_logo.svg",
        "leagueLogo": "Roshn_Saudi_League_Logo.svg"
    },
    {
        "id": "p_74",
        "name": "Leandro Trossard",
        "category": "Left Wingers / Midfielders (LW/LM)",
        "basePrice": "\u20b92M",
        "nation": "BELGIUM",
        "flagImg": "Flag_of_Belgium.svg",
        "pos": "LW",
        "rating": 83,
        "club": "ARSENAL",
        "clubImg": "Arsenal_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Leandro Trossard.png",
        "image": "Leandro Trossard.jpeg",
        "noBgImage": "no_bg/Leandro Trossard.png",
        "flag": "Flag_of_Belgium.svg",
        "clubLogo": "Arsenal_FC.svg",
        "leagueLogo": "Premier_League_Logo.svg"
    },
    {
        "id": "p_75",
        "name": "Mohamed Salah",
        "category": "Right Wingers / Midfielders (RW/RM)",
        "basePrice": "\u20b910M",
        "nation": "EGYPT",
        "flagImg": "Flag_of_Egypt.svg",
        "pos": "RW",
        "rating": 91,
        "club": "LIVERPOOL",
        "clubImg": "Liverpool_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Mohammed Salah.png",
        "image": "Mohammed Salah.jpeg",
        "noBgImage": "no_bg/Mohammed Salah.png",
        "flag": "Flag_of_Egypt.svg",
        "clubLogo": "Liverpool_FC.svg",
        "leagueLogo": "Premier_League_Logo.svg"
    },
    {
        "id": "p_76",
        "name": "Lamine Yamal",
        "category": "Right Wingers / Midfielders (RW/RM)",
        "basePrice": "\u20b910M",
        "nation": "SPAIN",
        "flagImg": "Flag_of_the_Kingdom_of_Spain.svg",
        "pos": "RW",
        "rating": 89,
        "club": "BARCELONA",
        "clubImg": "FC_Barcelona_(crest).svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Lamine Yamal.png",
        "image": "Lamine Yamal.jpeg",
        "noBgImage": "no_bg/Lamine Yamal.png",
        "flag": "Flag_of_the_Kingdom_of_Spain.svg",
        "clubLogo": "FC_Barcelona_(crest).svg",
        "leagueLogo": "LaLiga_EA_Sports_2023_Vertical_Logo.svg"
    },
    {
        "id": "p_77",
        "name": "Bukayo Saka",
        "category": "Right Wingers / Midfielders (RW/RM)",
        "basePrice": "\u20b97.5M",
        "nation": "ENGLAND",
        "flagImg": "Flag_of_England.svg",
        "pos": "RW",
        "rating": 88,
        "club": "ARSENAL",
        "clubImg": "Arsenal_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Bukayo Saka.png",
        "image": "Bukayo Saka.jpeg",
        "noBgImage": "no_bg/Bukayo Saka.png",
        "flag": "Flag_of_England.svg",
        "clubLogo": "Arsenal_FC.svg",
        "leagueLogo": "Premier_League_Logo.svg"
    },
    {
        "id": "p_78",
        "name": "Lionel Messi",
        "category": "Right Wingers / Midfielders (RW/RM)",
        "basePrice": "\u20b95M",
        "nation": "ARGENTINA",
        "flagImg": "Flag_of_Argentina.svg",
        "pos": "RW",
        "rating": 86,
        "club": "INTER MIAMI",
        "clubImg": "Inter_Miami_CF_logo.svg",
        "league": "MLS",
        "leagueImg": "Major_League_Soccer_logo.svg",
        "cardImg": "no_bg/Lionel Messi.png",
        "image": "Lionel Messi.jpeg",
        "noBgImage": "no_bg/Lionel Messi.png",
        "flag": "Flag_of_Argentina.svg",
        "clubLogo": "Inter_Miami_CF_logo.svg",
        "leagueLogo": "Major_League_Soccer_logo.svg"
    },
    {
        "id": "p_79",
        "name": "Michael Olise",
        "category": "Right Wingers / Midfielders (RW/RM)",
        "basePrice": "\u20b97.5M",
        "nation": "FRANCE",
        "flagImg": "Flag_of_France.svg",
        "pos": "RW",
        "rating": 86,
        "club": "BAYERN",
        "clubImg": "FC_Bayern_Munchen_logo.svg",
        "league": "BUNDESLIGA",
        "leagueImg": "Bundesliga_logo_(2017).svg",
        "cardImg": "no_bg/Michael Olise.png",
        "image": "Michael Olise.jpeg",
        "noBgImage": "no_bg/Michael Olise.png",
        "flag": "Flag_of_France.svg",
        "clubLogo": "FC_Bayern_Munchen_logo.svg",
        "leagueLogo": "Bundesliga_logo_(2017).svg"
    },
    {
        "id": "p_80",
        "name": "Phil Foden",
        "category": "Right Wingers / Midfielders (RW/RM)",
        "basePrice": "\u20b95M",
        "nation": "ENGLAND",
        "flagImg": "Flag_of_England.svg",
        "pos": "RW",
        "rating": 85,
        "club": "MANCHESTER CITY",
        "clubImg": "Manchester_City_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Phil Foden.png",
        "image": "Phil Foden.jpeg",
        "noBgImage": "no_bg/Phil Foden.png",
        "flag": "Flag_of_England.svg",
        "clubLogo": "Manchester_City_FC.svg",
        "leagueLogo": "Premier_League_Logo.svg"
    },
    {
        "id": "p_81",
        "name": "Desire Doue",
        "category": "Right Wingers / Midfielders (RW/RM)",
        "basePrice": "\u20b95M",
        "nation": "FRANCE",
        "flagImg": "Flag_of_France.svg",
        "pos": "RW",
        "rating": 85,
        "club": "PSG",
        "clubImg": "PSG_logo.svg",
        "league": "LIGUE 1",
        "leagueImg": "Logo_Ligue_1_McDonald_s_2024.svg",
        "cardImg": "no_bg/Desire Doue.png",
        "image": "Desire Doue.jpeg",
        "noBgImage": "no_bg/Desire Doue.png",
        "flag": "Flag_of_France.svg",
        "clubLogo": "PSG_logo.svg",
        "leagueLogo": "Logo_Ligue_1_McDonald_s_2024.svg"
    },
    {
        "id": "p_82",
        "name": "Rodrygo",
        "category": "Right Wingers / Midfielders (RW/RM)",
        "basePrice": "\u20b93M",
        "nation": "BRAZIL",
        "flagImg": "Flag_of_Brazil.svg",
        "pos": "RW",
        "rating": 85,
        "club": "REAL MADRID",
        "clubImg": "Real_Madrid_logo.svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Rodrygo Goes.png",
        "image": "Rodrygo Goes.jpeg",
        "noBgImage": "no_bg/Rodrygo Goes.png",
        "flag": "Flag_of_Brazil.svg",
        "clubLogo": "Real_Madrid_logo.svg",
        "leagueLogo": "LaLiga_EA_Sports_2023_Vertical_Logo.svg"
    },
    {
        "id": "p_83",
        "name": "Bryan Mbeumo",
        "category": "Right Wingers / Midfielders (RW/RM)",
        "basePrice": "\u20b93M",
        "nation": "CAMEROON",
        "flagImg": "Flag_of_Cameroon.svg",
        "pos": "RW",
        "rating": 85,
        "club": "MANCHESTER UNITED",
        "clubImg": "Manchester_United_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Bryan Mbuemo.png",
        "image": "Bryan Mbuemo.jpeg",
        "noBgImage": "no_bg/Bryan Mbuemo.png",
        "flag": "Flag_of_Cameroon.svg",
        "clubLogo": "Manchester_United_FC.svg",
        "leagueLogo": "Premier_League_Logo.svg"
    },
    {
        "id": "p_84",
        "name": "Christian Pulisic",
        "category": "Right Wingers / Midfielders (RW/RM)",
        "basePrice": "\u20b93M",
        "nation": "USA",
        "flagImg": "Flag_of_the_United_States_(DDD-F-416E_specifications).svg",
        "pos": "RW",
        "rating": 84,
        "club": "AC MILAN",
        "clubImg": "AC_Milan_logo.svg",
        "league": "SERIE A",
        "leagueImg": "Serie_A_ENILIVE_logo.svg",
        "cardImg": "no_bg/Christian Pulisic.png",
        "image": "Christian Pulisic.jpeg",
        "noBgImage": "no_bg/Christian Pulisic.png",
        "flag": "Flag_of_the_United_States_(DDD-F-416E_specifications).svg",
        "clubLogo": "AC_Milan_logo.svg",
        "leagueLogo": "Serie_A_ENILIVE_logo.svg"
    },
    {
        "id": "p_85",
        "name": "Moussa Diaby",
        "category": "Right Wingers / Midfielders (RW/RM)",
        "basePrice": "\u20b93M",
        "nation": "FRANCE",
        "flagImg": "Flag_of_France.svg",
        "pos": "RW",
        "rating": 84,
        "club": "AL ITIHAD",
        "clubImg": "Al-Ittihad_Club_(Jeddah)_logo.svg",
        "league": "SAUDI PRO LEAGUE",
        "leagueImg": "Roshn_Saudi_League_Logo.svg",
        "cardImg": "no_bg/Moussa Diaby.png",
        "image": "Moussa Diaby.jpeg",
        "noBgImage": "no_bg/Moussa Diaby.png",
        "flag": "Flag_of_France.svg",
        "clubLogo": "Al-Ittihad_Club_(Jeddah)_logo.svg",
        "leagueLogo": "Roshn_Saudi_League_Logo.svg"
    },
    {
        "id": "p_86",
        "name": "Brahim Diaz",
        "category": "Right Wingers / Midfielders (RW/RM)",
        "basePrice": "\u20b93M",
        "nation": "MOROCCO",
        "flagImg": "Flag_of_Morocco.svg",
        "pos": "RW",
        "rating": 82,
        "club": "REAL MADRID",
        "clubImg": "Real_Madrid_logo.svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Brahim Diaz.png",
        "image": "Brahim Diaz.jpeg",
        "noBgImage": "no_bg/Brahim Diaz.png",
        "flag": "Flag_of_Morocco.svg",
        "clubLogo": "Real_Madrid_logo.svg",
        "leagueLogo": "LaLiga_EA_Sports_2023_Vertical_Logo.svg"
    },
    {
        "id": "p_87",
        "name": "Karim Adeyemi",
        "category": "Right Wingers / Midfielders (RW/RM)",
        "basePrice": "\u20b93M",
        "nation": "GERMANY",
        "flagImg": "Flag_of_Germany.svg",
        "pos": "RW",
        "rating": 84,
        "club": "DORTMUND",
        "clubImg": "Borussia_Dortmund_logo.svg",
        "league": "BUNDESLIGA",
        "leagueImg": "Bundesliga_logo_(2017).svg",
        "cardImg": "no_bg/Karim Adeyemi.png",
        "image": "Karim Adeyemi.jpeg",
        "noBgImage": "no_bg/Karim Adeyemi.png",
        "flag": "Flag_of_Germany.svg",
        "clubLogo": "Borussia_Dortmund_logo.svg",
        "leagueLogo": "Bundesliga_logo_(2017).svg"
    },
    {
        "id": "p_88",
        "name": "Leroy Sane",
        "category": "Right Wingers / Midfielders (RW/RM)",
        "basePrice": "\u20b92M",
        "nation": "GERMANY",
        "flagImg": "Flag_of_Germany.svg",
        "pos": "RW / CAM",
        "rating": 82,
        "club": "GALATASARAY",
        "clubImg": "Galatasaray_SK_logo.svg",
        "league": "S\u00dcPER LIG",
        "leagueImg": "Turkish_Su\u0308per_Lig_logo_(2024).svg",
        "cardImg": "no_bg/Leroy Sane.png",
        "image": "Leroy Sane.jpeg",
        "noBgImage": "no_bg/Leroy Sane.png",
        "flag": "Flag_of_Germany.svg",
        "clubLogo": "Galatasaray_SK_logo.svg",
        "leagueLogo": "Turkish_Su\u0308per_Lig_logo_(2024).svg"
    },
    {
        "id": "p_89",
        "name": "Rayan Cherki",
        "category": "Right Wingers / Midfielders (RW/RM)",
        "basePrice": "\u20b92M",
        "nation": "FRANCE",
        "flagImg": "Flag_of_France.svg",
        "pos": "RW / CAM",
        "rating": 81,
        "club": "MANCHESTER CITY",
        "clubImg": "Manchester_City_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Rayan Cherki.png",
        "image": "Rayan Cherki.jpeg",
        "noBgImage": "no_bg/Rayan Cherki.png",
        "flag": "Flag_of_France.svg",
        "clubLogo": "Manchester_City_FC.svg",
        "leagueLogo": "Premier_League_Logo.svg"
    },
    {
        "id": "p_90",
        "name": "Kylian Mbappe",
        "category": "Strikers (ST)",
        "basePrice": "\u20b910M",
        "nation": "FRANCE",
        "flagImg": "Flag_of_France.svg",
        "pos": "ST",
        "rating": 91,
        "club": "REAL MADRID",
        "clubImg": "Real_Madrid_logo.svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Kylian Mbappe.png",
        "image": "Kylian Mbappe.jpeg",
        "noBgImage": "no_bg/Kylian Mbappe.png",
        "flag": "Flag_of_France.svg",
        "clubLogo": "Real_Madrid_logo.svg",
        "leagueLogo": "LaLiga_EA_Sports_2023_Vertical_Logo.svg"
    },
    {
        "id": "p_91",
        "name": "Erling Haaland",
        "category": "Strikers (ST)",
        "basePrice": "\u20b910M",
        "nation": "NORWAY",
        "flagImg": "Flag_of_Norway.svg",
        "pos": "ST",
        "rating": 90,
        "club": "MANCHESTER CITY",
        "clubImg": "Manchester_City_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Erling Haaland.png",
        "image": "Erling Haaland.jpeg",
        "noBgImage": "no_bg/Erling Haaland.png",
        "flag": "Flag_of_Norway.svg",
        "clubLogo": "Manchester_City_FC.svg",
        "leagueLogo": "Premier_League_Logo.svg"
    },
    {
        "id": "p_92",
        "name": "Harry Kane",
        "category": "Strikers (ST)",
        "basePrice": "\u20b97.5M",
        "nation": "ENGLAND",
        "flagImg": "Flag_of_England.svg",
        "pos": "ST",
        "rating": 89,
        "club": "BAYERN",
        "clubImg": "FC_Bayern_Munchen_logo.svg",
        "league": "BUNDESLIGA",
        "leagueImg": "Bundesliga_logo_(2017).svg",
        "cardImg": "no_bg/Harry Kane.png",
        "image": "Harry Kane.jpeg",
        "noBgImage": "no_bg/Harry Kane.png",
        "flag": "Flag_of_England.svg",
        "clubLogo": "FC_Bayern_Munchen_logo.svg",
        "leagueLogo": "Bundesliga_logo_(2017).svg"
    },
    {
        "id": "p_93",
        "name": "Ousmane Dembele",
        "category": "Strikers (ST)",
        "basePrice": "\u20b910M",
        "nation": "FRANCE",
        "flagImg": "Flag_of_France.svg",
        "pos": "ST",
        "rating": 90,
        "club": "PSG",
        "clubImg": "PSG_logo.svg",
        "league": "LIGUE 1",
        "leagueImg": "Logo_Ligue_1_McDonald_s_2024.svg",
        "cardImg": "no_bg/Ousmane Dembele.png",
        "image": "Ousmane Dembele.jpeg",
        "noBgImage": "no_bg/Ousmane Dembele.png",
        "flag": "Flag_of_France.svg",
        "clubLogo": "PSG_logo.svg",
        "leagueLogo": "Logo_Ligue_1_McDonald_s_2024.svg"
    },
    {
        "id": "p_94",
        "name": "Lautaro Martinez",
        "category": "Strikers (ST)",
        "basePrice": "\u20b97.5M",
        "nation": "ARGENTINA",
        "flagImg": "Flag_of_Argentina.svg",
        "pos": "ST",
        "rating": 88,
        "club": "INTER MILAN",
        "clubImg": "FC_Internazionale_Milano_2021.svg",
        "league": "SERIE A",
        "leagueImg": "Serie_A_ENILIVE_logo.svg",
        "cardImg": "no_bg/Lautaro Martinez.png",
        "image": "Lautaro Martinez.jpeg",
        "noBgImage": "no_bg/Lautaro Martinez.png",
        "flag": "Flag_of_Argentina.svg",
        "clubLogo": "FC_Internazionale_Milano_2021.svg",
        "leagueLogo": "Serie_A_ENILIVE_logo.svg"
    },
    {
        "id": "p_95",
        "name": "Alexander Isak",
        "category": "Strikers (ST)",
        "basePrice": "\u20b97.5M",
        "nation": "SWEDEN",
        "flagImg": "Flag_of_Sweden.svg",
        "pos": "ST",
        "rating": 88,
        "club": "LIVERPOOL",
        "clubImg": "Liverpool_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Alexander Isak.png",
        "image": "Alexander Isak.jpeg",
        "noBgImage": "no_bg/Alexander Isak.png",
        "flag": "Flag_of_Sweden.svg",
        "clubLogo": "Liverpool_FC.svg",
        "leagueLogo": "Premier_League_Logo.svg"
    },
    {
        "id": "p_96",
        "name": "Viktor Gyokeres",
        "category": "Strikers (ST)",
        "basePrice": "\u20b97.5M",
        "nation": "SWEDEN",
        "flagImg": "Flag_of_Sweden.svg",
        "pos": "ST",
        "rating": 87,
        "club": "ARSENAL",
        "clubImg": "Arsenal_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Viktor Gyokeres.png",
        "image": "Viktor Gyokeres.jpeg",
        "noBgImage": "no_bg/Viktor Gyokeres.png",
        "flag": "Flag_of_Sweden.svg",
        "clubLogo": "Arsenal_FC.svg",
        "leagueLogo": "Premier_League_Logo.svg"
    },
    {
        "id": "p_97",
        "name": "Julian Alvarez",
        "category": "Strikers (ST)",
        "basePrice": "\u20b97.5M",
        "nation": "ARGENTINA",
        "flagImg": "Flag_of_Argentina.svg",
        "pos": "ST",
        "rating": 87,
        "club": "ATLETICO MADRID",
        "clubImg": "Atletico_Madrid_Logo_2024.svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Alvarez.png",
        "image": "Alvarez.jpeg",
        "noBgImage": "no_bg/Alvarez.png",
        "flag": "Flag_of_Argentina.svg",
        "clubLogo": "Atletico_Madrid_Logo_2024.svg",
        "leagueLogo": "LaLiga_EA_Sports_2023_Vertical_Logo.svg"
    },
    {
        "id": "p_98",
        "name": "Robert Lewandowski",
        "category": "Strikers (ST)",
        "basePrice": "\u20b97.5M",
        "nation": "POLAND",
        "flagImg": "Flag_of_Poland.svg",
        "pos": "ST",
        "rating": 88,
        "club": "BARCELONA",
        "clubImg": "FC_Barcelona_(crest).svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Robert Lewandowski.png",
        "image": "Robert Lewandowski.jpeg",
        "noBgImage": "no_bg/Robert Lewandowski.png",
        "flag": "Flag_of_Poland.svg",
        "clubLogo": "FC_Barcelona_(crest).svg",
        "leagueLogo": "LaLiga_EA_Sports_2023_Vertical_Logo.svg"
    },
    {
        "id": "p_99",
        "name": "Cristiano Ronaldo",
        "category": "Strikers (ST)",
        "basePrice": "\u20b97.5M",
        "nation": "PORTUGAL",
        "flagImg": "Flag_of_Portugal_(official).svg",
        "pos": "ST",
        "rating": 85,
        "club": "AL NASSER",
        "clubImg": "Al_Nassr_FC_logo.svg",
        "league": "SAUDI PRO LEAGUE",
        "leagueImg": "Roshn_Saudi_League_Logo.svg",
        "cardImg": "no_bg/Cristiano Ronaldo.png",
        "image": "Cristiano Ronaldo.jpeg",
        "noBgImage": "no_bg/Cristiano Ronaldo.png",
        "flag": "Flag_of_Portugal_(official).svg",
        "clubLogo": "Al_Nassr_FC_logo.svg",
        "leagueLogo": "Roshn_Saudi_League_Logo.svg"
    },
    {
        "id": "p_100",
        "name": "Victor Osimhen",
        "category": "Strikers (ST)",
        "basePrice": "\u20b97.5M",
        "nation": "NIGERIA",
        "flagImg": "Flag_of_Nigeria.svg",
        "pos": "ST",
        "rating": 87,
        "club": "GALATASARAY",
        "clubImg": "Galatasaray_SK_logo.svg",
        "league": "TURKISH S\u00dcPER LIG",
        "leagueImg": "Turkish_Su\u0308per_Lig_logo_(2024).svg",
        "cardImg": "no_bg/Victor Osimhen.png",
        "image": "Victor Osimhen.jpeg",
        "noBgImage": "no_bg/Victor Osimhen.png",
        "flag": "Flag_of_Nigeria.svg",
        "clubLogo": "Galatasaray_SK_logo.svg",
        "leagueLogo": "Turkish_Su\u0308per_Lig_logo_(2024).svg"
    }
];
const playersData = PLAYERS_DATABASE;

if (typeof module !== 'undefined' && module.exports) {
    module.exports = PLAYERS_DATABASE;
}
